# Generated by Django 2.0.2 on 2018-06-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EnlaceBellbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('enlace', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(default='logos/logo.jpg', upload_to='logos/')),
                ('departamento', models.ManyToManyField(to='AppsBellbank.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permisos', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='enlacebellbank',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppsBellbank.Estados'),
        ),
        migrations.AddField(
            model_name='enlacebellbank',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppsBellbank.Permisos'),
        ),
    ]
