# Generated by Django 2.0.2 on 2018-03-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppsBellbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enlace',
            new_name='EnlaceCursos',
        ),
    ]
