# Generated by Django 2.0 on 2018-03-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsBellbank', '0003_enlacebellbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
    ]
