# Generated by Django 2.0 on 2018-03-07 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppsBellbank', '0004_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacebellbank',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppsBellbank.Estados'),
        ),
    ]
