# Generated by Django 2.0.2 on 2018-03-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsBellbank', '0006_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='permiso',
            field=models.CharField(max_length=10),
        ),
    ]
