# Generated by Django 2.0.2 on 2018-03-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppsBellbank', '0007_auto_20180307_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisos',
            old_name='permiso',
            new_name='permisos',
        ),
    ]
