# Generated by Django 2.0.2 on 2018-03-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsBellbank', '0008_auto_20180307_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='permisos',
            field=models.CharField(max_length=15),
        ),
    ]
