# Generated by Django 2.0.2 on 2018-03-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppsBellbank', '0009_auto_20180307_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacebellbank',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppsBellbank.Permisos'),
        ),
    ]
