# Generated by Django 2.0.2 on 2018-03-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppsBellbank', '0010_enlacebellbank_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacebellbank',
            name='logo',
            field=models.ImageField(default='logos/logo.jpg', upload_to='logos/'),
        ),
    ]
